INSERT INTO questions (title, topic, difficulty, slug, is_global, owner_id) VALUES
  ('Contains Duplicate', 'arrays', 'easy', 'contains-duplicate', TRUE, NULL),
  ('Valid Anagram', 'strings', 'easy', 'valid-anagram', TRUE, NULL),
  ('Two Sum', 'arrays', 'easy', 'two-sum', TRUE, NULL),
  ('Group Anagrams', 'strings', 'medium', 'group-anagrams', TRUE, NULL),
  ('Top K Frequent Elements', 'arrays', 'medium', 'top-k-frequent-elements', TRUE, NULL),
  ('Product of Array Except Self', 'arrays', 'medium', 'product-of-array-except-self', TRUE, NULL),
  ('Valid Sudoku', 'arrays', 'medium', 'valid-sudoku', TRUE, NULL),
  ('Encode and Decode Strings', 'strings', 'medium', 'encode-and-decode-strings', TRUE, NULL),
  ('Longest Consecutive Sequence', 'arrays', 'medium', 'longest-consecutive-sequence', TRUE, NULL),
  ('Valid Palindrome', 'strings', 'easy', 'valid-palindrome', TRUE, NULL),
  ('Two Sum II', 'arrays', 'medium', 'two-sum-ii-input-array-is-sorted', TRUE, NULL),
  ('3Sum', 'arrays', 'medium', '3sum', TRUE, NULL),
  ('Container With Most Water', 'arrays', 'medium', 'container-with-most-water', TRUE, NULL),
  ('Trapping Rain Water', 'arrays', 'hard', 'trapping-rain-water', TRUE, NULL),
  ('Best Time to Buy and Sell Stock', 'arrays', 'easy', 'best-time-to-buy-and-sell-stock', TRUE, NULL),
  ('Longest Substring Without Repeating Characters', 'strings', 'medium', 'longest-substring-without-repeating-characters', TRUE, NULL),
  ('Longest Repeating Character Replacement', 'strings', 'medium', 'longest-repeating-character-replacement', TRUE, NULL),
  ('Permutation in String', 'strings', 'medium', 'permutation-in-string', TRUE, NULL),
  ('Minimum Window Substring', 'strings', 'hard', 'minimum-window-substring', TRUE, NULL),
  ('Sliding Window Maximum', 'arrays', 'hard', 'sliding-window-maximum', TRUE, NULL),
  ('Valid Parentheses', 'stack', 'easy', 'valid-parentheses', TRUE, NULL),
  ('Min Stack', 'stack', 'medium', 'min-stack', TRUE, NULL),
  ('Evaluate Reverse Polish Notation', 'stack', 'medium', 'evaluate-reverse-polish-notation', TRUE, NULL),
  ('Generate Parentheses', 'stack', 'medium', 'generate-parentheses', TRUE, NULL),
  ('Daily Temperatures', 'stack', 'medium', 'daily-temperatures', TRUE, NULL),
  ('Car Fleet', 'stack', 'medium', 'car-fleet', TRUE, NULL),
  ('Largest Rectangle in Histogram', 'stack', 'hard', 'largest-rectangle-in-histogram', TRUE, NULL),
  ('Binary Search', 'binary-search', 'easy', 'binary-search', TRUE, NULL),
  ('Search a 2D Matrix', 'binary-search', 'medium', 'search-a-2d-matrix', TRUE, NULL),
  ('Koko Eating Bananas', 'binary-search', 'medium', 'koko-eating-bananas', TRUE, NULL),
  ('Find Minimum in Rotated Sorted Array', 'binary-search', 'medium', 'find-minimum-in-rotated-sorted-array', TRUE, NULL),
  ('Search in Rotated Sorted Array', 'binary-search', 'medium', 'search-in-rotated-sorted-array', TRUE, NULL),
  ('Time Based Key-Value Store', 'binary-search', 'medium', 'time-based-key-value-store', TRUE, NULL),
  ('Median of Two Sorted Arrays', 'binary-search', 'hard', 'median-of-two-sorted-arrays', TRUE, NULL),
  ('Reverse Linked List', 'linked-list', 'easy', 'reverse-linked-list', TRUE, NULL),
  ('Merge Two Sorted Lists', 'linked-list', 'easy', 'merge-two-sorted-lists', TRUE, NULL),
  ('Reorder List', 'linked-list', 'medium', 'reorder-list', TRUE, NULL),
  ('Remove Nth Node From End of List', 'linked-list', 'medium', 'remove-nth-node-from-end-of-list', TRUE, NULL),
  ('Copy List with Random Pointer', 'linked-list', 'medium', 'copy-list-with-random-pointer', TRUE, NULL),
  ('Add Two Numbers', 'linked-list', 'medium', 'add-two-numbers', TRUE, NULL),
  ('Linked List Cycle', 'linked-list', 'easy', 'linked-list-cycle', TRUE, NULL),
  ('Find the Duplicate Number', 'linked-list', 'medium', 'find-the-duplicate-number', TRUE, NULL),
  ('LRU Cache', 'linked-list', 'medium', 'lru-cache', TRUE, NULL),
  ('Merge K Sorted Lists', 'linked-list', 'hard', 'merge-k-sorted-lists', TRUE, NULL),
  ('Reverse Nodes in K-Group', 'linked-list', 'hard', 'reverse-nodes-in-k-group', TRUE, NULL),
  ('Invert Binary Tree', 'trees', 'easy', 'invert-binary-tree', TRUE, NULL),
  ('Maximum Depth of Binary Tree', 'trees', 'easy', 'maximum-depth-of-binary-tree', TRUE, NULL),
  ('Diameter of Binary Tree', 'trees', 'easy', 'diameter-of-binary-tree', TRUE, NULL),
  ('Balanced Binary Tree', 'trees', 'easy', 'balanced-binary-tree', TRUE, NULL),
  ('Same Tree', 'trees', 'easy', 'same-tree', TRUE, NULL),
  ('Subtree of Another Tree', 'trees', 'easy', 'subtree-of-another-tree', TRUE, NULL),
  ('Lowest Common Ancestor of a BST', 'trees', 'medium', 'lowest-common-ancestor-of-a-binary-search-tree', TRUE, NULL),
  ('Binary Tree Level Order Traversal', 'trees', 'medium', 'binary-tree-level-order-traversal', TRUE, NULL),
  ('Binary Tree Right Side View', 'trees', 'medium', 'binary-tree-right-side-view', TRUE, NULL),
  ('Count Good Nodes in Binary Tree', 'trees', 'medium', 'count-good-nodes-in-binary-tree', TRUE, NULL),
  ('Validate Binary Search Tree', 'trees', 'medium', 'validate-binary-search-tree', TRUE, NULL),
  ('Kth Smallest Element in a BST', 'trees', 'medium', 'kth-smallest-element-in-a-bst', TRUE, NULL),
  ('Construct Binary Tree from Preorder and Inorder Traversal', 'trees', 'medium', 'construct-binary-tree-from-preorder-and-inorder-traversal', TRUE, NULL),
  ('Binary Tree Maximum Path Sum', 'trees', 'hard', 'binary-tree-maximum-path-sum', TRUE, NULL),
  ('Serialize and Deserialize Binary Tree', 'trees', 'hard', 'serialize-and-deserialize-binary-tree', TRUE, NULL),
  ('Implement Trie', 'trees', 'medium', 'implement-trie-prefix-tree', TRUE, NULL),
  ('Design Add and Search Words Data Structure', 'trees', 'medium', 'design-add-and-search-words-data-structure', TRUE, NULL),
  ('Word Search II', 'trees', 'hard', 'word-search-ii', TRUE, NULL),
  ('Kth Largest Element in a Stream', 'heap', 'easy', 'kth-largest-element-in-a-stream', TRUE, NULL),
  ('Last Stone Weight', 'heap', 'easy', 'last-stone-weight', TRUE, NULL),
  ('K Closest Points to Origin', 'heap', 'medium', 'k-closest-points-to-origin', TRUE, NULL),
  ('Kth Largest Element in an Array', 'heap', 'medium', 'kth-largest-element-in-an-array', TRUE, NULL),
  ('Task Scheduler', 'heap', 'medium', 'task-scheduler', TRUE, NULL),
  ('Design Twitter', 'heap', 'medium', 'design-twitter', TRUE, NULL),
  ('Find Median from Data Stream', 'heap', 'hard', 'find-median-from-data-stream', TRUE, NULL),
  ('Subsets', 'backtracking', 'medium', 'subsets', TRUE, NULL),
  ('Combination Sum', 'backtracking', 'medium', 'combination-sum', TRUE, NULL),
  ('Permutations', 'backtracking', 'medium', 'permutations', TRUE, NULL),
  ('Subsets II', 'backtracking', 'medium', 'subsets-ii', TRUE, NULL),
  ('Combination Sum II', 'backtracking', 'medium', 'combination-sum-ii', TRUE, NULL),
  ('Word Search', 'backtracking', 'medium', 'word-search', TRUE, NULL),
  ('Palindrome Partitioning', 'backtracking', 'medium', 'palindrome-partitioning', TRUE, NULL),
  ('Letter Combinations of a Phone Number', 'backtracking', 'medium', 'letter-combinations-of-a-phone-number', TRUE, NULL),
  ('N-Queens', 'backtracking', 'hard', 'n-queens', TRUE, NULL),
  ('Number of Islands', 'graphs', 'medium', 'number-of-islands', TRUE, NULL),
  ('Clone Graph', 'graphs', 'medium', 'clone-graph', TRUE, NULL),
  ('Max Area of Island', 'graphs', 'medium', 'max-area-of-island', TRUE, NULL),
  ('Pacific Atlantic Water Flow', 'graphs', 'medium', 'pacific-atlantic-water-flow', TRUE, NULL),
  ('Surrounded Regions', 'graphs', 'medium', 'surrounded-regions', TRUE, NULL),
  ('Rotting Oranges', 'graphs', 'medium', 'rotting-oranges', TRUE, NULL),
  ('Walls and Gates', 'graphs', 'medium', 'walls-and-gates', TRUE, NULL),
  ('Course Schedule', 'graphs', 'medium', 'course-schedule', TRUE, NULL),
  ('Course Schedule II', 'graphs', 'medium', 'course-schedule-ii', TRUE, NULL),
  ('Redundant Connection', 'graphs', 'medium', 'redundant-connection', TRUE, NULL),
  ('Number of Connected Components in an Undirected Graph', 'graphs', 'medium', 'number-of-connected-components-in-an-undirected-graph', TRUE, NULL),
  ('Graph Valid Tree', 'graphs', 'medium', 'graph-valid-tree', TRUE, NULL),
  ('Word Ladder', 'graphs', 'hard', 'word-ladder', TRUE, NULL),
  ('Reconstruct Itinerary', 'graphs', 'hard', 'reconstruct-itinerary', TRUE, NULL),
  ('Min Cost to Connect All Points', 'graphs', 'medium', 'min-cost-to-connect-all-points', TRUE, NULL),
  ('Network Delay Time', 'graphs', 'medium', 'network-delay-time', TRUE, NULL),
  ('Swim in Rising Water', 'graphs', 'hard', 'swim-in-rising-water', TRUE, NULL),
  ('Alien Dictionary', 'graphs', 'hard', 'alien-dictionary', TRUE, NULL),
  ('Cheapest Flights Within K Stops', 'graphs', 'medium', 'cheapest-flights-within-k-stops', TRUE, NULL),
  ('Climbing Stairs', 'dp', 'easy', 'climbing-stairs', TRUE, NULL),
  ('Min Cost Climbing Stairs', 'dp', 'easy', 'min-cost-climbing-stairs', TRUE, NULL),
  ('House Robber', 'dp', 'medium', 'house-robber', TRUE, NULL),
  ('House Robber II', 'dp', 'medium', 'house-robber-ii', TRUE, NULL),
  ('Longest Palindromic Substring', 'dp', 'medium', 'longest-palindromic-substring', TRUE, NULL),
  ('Palindromic Substrings', 'dp', 'medium', 'palindromic-substrings', TRUE, NULL),
  ('Decode Ways', 'dp', 'medium', 'decode-ways', TRUE, NULL),
  ('Coin Change', 'dp', 'medium', 'coin-change', TRUE, NULL),
  ('Maximum Product Subarray', 'dp', 'medium', 'maximum-product-subarray', TRUE, NULL),
  ('Word Break', 'dp', 'medium', 'word-break', TRUE, NULL),
  ('Longest Increasing Subsequence', 'dp', 'medium', 'longest-increasing-subsequence', TRUE, NULL),
  ('Partition Equal Subset Sum', 'dp', 'medium', 'partition-equal-subset-sum', TRUE, NULL),
  ('Unique Paths', 'dp', 'medium', 'unique-paths', TRUE, NULL),
  ('Longest Common Subsequence', 'dp', 'medium', 'longest-common-subsequence', TRUE, NULL),
  ('Best Time to Buy and Sell Stock With Cooldown', 'dp', 'medium', 'best-time-to-buy-and-sell-stock-with-cooldown', TRUE, NULL),
  ('Coin Change II', 'dp', 'medium', 'coin-change-2', TRUE, NULL),
  ('Target Sum', 'dp', 'medium', 'target-sum', TRUE, NULL),
  ('Interleaving String', 'dp', 'medium', 'interleaving-string', TRUE, NULL),
  ('Longest Increasing Path in a Matrix', 'dp', 'hard', 'longest-increasing-path-in-a-matrix', TRUE, NULL),
  ('Distinct Subsequences', 'dp', 'hard', 'distinct-subsequences', TRUE, NULL),
  ('Edit Distance', 'dp', 'medium', 'edit-distance', TRUE, NULL),
  ('Burst Balloons', 'dp', 'hard', 'burst-balloons', TRUE, NULL),
  ('Regular Expression Matching', 'dp', 'hard', 'regular-expression-matching', TRUE, NULL),
  ('Maximum Subarray', 'dp', 'medium', 'maximum-subarray', TRUE, NULL),
  ('Jump Game', 'dp', 'medium', 'jump-game', TRUE, NULL),
  ('Jump Game II', 'dp', 'medium', 'jump-game-ii', TRUE, NULL),
  ('Gas Station', 'dp', 'medium', 'gas-station', TRUE, NULL),
  ('Hand of Straights', 'arrays', 'medium', 'hand-of-straights', TRUE, NULL),
  ('Merge Triplets to Form Target Triplet', 'arrays', 'medium', 'merge-triplets-to-form-target-triplet', TRUE, NULL),
  ('Partition Labels', 'strings', 'medium', 'partition-labels', TRUE, NULL),
  ('Valid Parenthesis String', 'stack', 'medium', 'valid-parenthesis-string', TRUE, NULL),
  ('Insert Interval', 'arrays', 'medium', 'insert-interval', TRUE, NULL),
  ('Merge Intervals', 'arrays', 'medium', 'merge-intervals', TRUE, NULL),
  ('Non-overlapping Intervals', 'arrays', 'medium', 'non-overlapping-intervals', TRUE, NULL),
  ('Meeting Rooms', 'arrays', 'easy', 'meeting-rooms', TRUE, NULL),
  ('Meeting Rooms II', 'arrays', 'medium', 'meeting-rooms-ii', TRUE, NULL),
  ('Minimum Interval to Include Each Query', 'arrays', 'hard', 'minimum-interval-to-include-each-query', TRUE, NULL),
  ('Rotate Image', 'arrays', 'medium', 'rotate-image', TRUE, NULL),
  ('Spiral Matrix', 'arrays', 'medium', 'spiral-matrix', TRUE, NULL),
  ('Set Matrix Zeroes', 'arrays', 'medium', 'set-matrix-zeroes', TRUE, NULL),
  ('Happy Number', 'arrays', 'easy', 'happy-number', TRUE, NULL),
  ('Plus One', 'arrays', 'easy', 'plus-one', TRUE, NULL),
  ('Pow(x, n)', 'binary-search', 'medium', 'powx-n', TRUE, NULL),
  ('Multiply Strings', 'strings', 'medium', 'multiply-strings', TRUE, NULL),
  ('Detect Squares', 'arrays', 'medium', 'detect-squares', TRUE, NULL),
  ('Single Number', 'arrays', 'easy', 'single-number', TRUE, NULL),
  ('Number of 1 Bits', 'bit-manipulation', 'easy', 'number-of-1-bits', TRUE, NULL),
  ('Counting Bits', 'bit-manipulation', 'easy', 'counting-bits', TRUE, NULL),
  ('Reverse Bits', 'bit-manipulation', 'easy', 'reverse-bits', TRUE, NULL),
  ('Missing Number', 'bit-manipulation', 'easy', 'missing-number', TRUE, NULL),
  ('Sum of Two Integers', 'bit-manipulation', 'medium', 'sum-of-two-integers', TRUE, NULL),
  ('Reverse Integer', 'bit-manipulation', 'medium', 'reverse-integer', TRUE, NULL);