ALTER TABLE questions ADD COLUMN description TEXT;

UPDATE questions q
SET description = v.description
FROM (VALUES
  ('contains-duplicate', 'Check if any value appears at least twice in an integer array.'),
  ('valid-anagram', 'Determine if two strings share the exact same character counts.'),
  ('two-sum', 'Find the indices of two numbers in an array that add up to a specific target.'),
  ('group-anagrams', 'Cluster a list of strings by their shared anagram groupings.'),
  ('top-k-frequent-elements', 'Return the k most common elements in an integer array.'),
  ('product-of-array-except-self', 'Return an array where each element is the product of all other elements without using division.'),
  ('valid-sudoku', 'Validate the current state of a partially filled 9x9 Sudoku board.'),
  ('encode-and-decode-strings', 'Design a reversible algorithm to serialize and deserialize an array of strings.'),
  ('longest-consecutive-sequence', 'Find the length of the longest consecutive sequence of numbers in an unsorted array in O(n) time.'),
  ('valid-palindrome', 'Check if a string reads the same forwards and backwards, ignoring non-alphanumeric characters.'),
  ('two-sum-ii-input-array-is-sorted', 'Find two numbers summing to a target in a 1-indexed, strictly sorted array.'),
  ('3sum', 'Find all unique triplets in an array that sum to exactly zero.'),
  ('container-with-most-water', 'Maximize the area of water that can be trapped between two vertical lines on a graph.'),
  ('trapping-rain-water', 'Calculate the total volume of water trapped between complex terrain elevations after raining.'),
  ('best-time-to-buy-and-sell-stock', 'Find the maximum profit achievable from a single buy and sell operation.'),
  ('longest-substring-without-repeating-characters', 'Find the length of the longest unique character sequence in a string.'),
  ('longest-repeating-character-replacement', 'Maximize a single-character sequence by replacing at most k characters.'),
  ('permutation-in-string', 'Check if a string contains a contiguous permutation of a target string.'),
  ('minimum-window-substring', 'Find the smallest substring that contains all characters (including duplicates) of another string.'),
  ('sliding-window-maximum', 'Return the maximum element visible in every sliding window of size k.'),
  ('valid-parentheses', 'Ensure a string of brackets is properly closed and nested.'),
  ('min-stack', 'Implement a stack that supports retrieving the minimum element in constant O(1) time.'),
  ('evaluate-reverse-polish-notation', 'Calculate the mathematical result of an expression written in postfix notation.'),
  ('generate-parentheses', 'Generate all valid, well-formed combinations of n pairs of parentheses.'),
  ('daily-temperatures', 'Calculate how many days you must wait until a warmer temperature for each day in an array.'),
  ('car-fleet', 'Calculate how many distinct car fleets will reach a target destination given varying speeds and positions.'),
  ('largest-rectangle-in-histogram', 'Find the rectangular area of the largest bounding box within a histogram.'),
  ('binary-search', 'Implement a standard O(log n) search in a sorted array.'),
  ('search-a-2d-matrix', 'Efficiently search for a target value in a fully sorted 2D grid.'),
  ('koko-eating-bananas', 'Find the minimum eating speed required to finish all bananas within h hours.'),
  ('find-minimum-in-rotated-sorted-array', 'Locate the lowest value in a sorted array that has been shifted.'),
  ('search-in-rotated-sorted-array', 'Find a target value''s index in a shifted sorted array.'),
  ('time-based-key-value-store', 'Retrieve the value of a key based on the largest timestamp less than or equal to a target timestamp.'),
  ('median-of-two-sorted-arrays', 'Find the median of two separate sorted arrays in O(log(m+n)) time.'),
  ('reverse-linked-list', 'Completely reverse the direction of a singly linked list.'),
  ('merge-two-sorted-lists', 'Interleave two sorted linked lists into a single sorted list.'),
  ('reorder-list', 'Fold a linked list in half, alternating nodes from the start and the end.'),
  ('remove-nth-node-from-end-of-list', 'Delete the nth node from the tail of the list in one pass.'),
  ('copy-list-with-random-pointer', 'Create a deep copy of a linked list where nodes contain arbitrary random pointers.'),
  ('add-two-numbers', 'Sum two integers represented as reversed linked lists and return the result in the same format.'),
  ('linked-list-cycle', 'Detect if a linked list contains a continuous loop.'),
  ('find-the-duplicate-number', 'Find the single duplicate integer in an array using Floyd''s cycle-finding algorithm.'),
  ('lru-cache', 'Implement a Least Recently Used (LRU) caching mechanism with O(1) operations.'),
  ('merge-k-sorted-lists', 'Efficiently combine k sorted linked lists into a single continuous sorted list.'),
  ('reverse-nodes-in-k-group', 'Reverse consecutive segments of k nodes throughout a linked list.'),
  ('invert-binary-tree', 'Swap all left and right children to create a mirror image of a binary tree.'),
  ('maximum-depth-of-binary-tree', 'Count the maximum number of nodes along the longest path from root to leaf.'),
  ('diameter-of-binary-tree', 'Find the length of the longest path between any two nodes in a tree.'),
  ('balanced-binary-tree', 'Check if the depths of every node''s left and right subtrees differ by at most one.'),
  ('same-tree', 'Determine if two binary trees are structurally identical with identical values.'),
  ('subtree-of-another-tree', 'Check if one tree''s structure and values exist entirely within another tree.'),
  ('lowest-common-ancestor-of-a-binary-search-tree', 'Find the deepest shared parent of two specific nodes in a Binary Search Tree.'),
  ('binary-tree-level-order-traversal', 'Group tree nodes layer by layer from top to bottom.'),
  ('binary-tree-right-side-view', 'Return an array of the nodes visible when looking at the tree from the right side.'),
  ('count-good-nodes-in-binary-tree', 'Count nodes whose value is greater than or equal to all previous ancestors in its path.'),
  ('validate-binary-search-tree', 'Ensure a tree strictly adheres to all left/right BST ordering rules.'),
  ('kth-smallest-element-in-a-bst', 'Find the kth smallest numerical value in a Binary Search Tree.'),
  ('construct-binary-tree-from-preorder-and-inorder-traversal', 'Rebuild a complete tree structure using its traversal outputs.'),
  ('binary-tree-maximum-path-sum', 'Find the continuous path with the highest possible sum of node values.'),
  ('serialize-and-deserialize-binary-tree', 'Design an algorithm to convert a tree to a string and safely reconstruct it.'),
  ('implement-trie-prefix-tree', 'Build a prefix tree supporting efficient insert, search, and startsWith operations.'),
  ('design-add-and-search-words-data-structure', 'Implement a dictionary supporting wildcard . character searches.'),
  ('word-search-ii', 'Find all words from a given dictionary that can be traced in a 2D board of characters.'),
  ('kth-largest-element-in-a-stream', 'Dynamically maintain and return the kth largest element in an ongoing data stream.'),
  ('last-stone-weight', 'Simulate continually smashing the two heaviest stones together until one or none remain.'),
  ('k-closest-points-to-origin', 'Find the k coordinates geometrically closest to (0,0).'),
  ('kth-largest-element-in-an-array', 'Find the kth largest value in an array without fully sorting it.'),
  ('task-scheduler', 'Calculate the minimum CPU time required to finish tasks given a mandatory cooldown period between identical tasks.'),
  ('design-twitter', 'Implement a simplified version of posting tweets, following users, and fetching a chronological feed.'),
  ('find-median-from-data-stream', 'Efficiently track and retrieve the median value of a dynamically growing list of numbers.'),
  ('subsets', 'Generate all possible power sets of a unique integer array.'),
  ('combination-sum', 'Find all configurations of numbers that sum to a target value (numbers can be reused).'),
  ('permutations', 'Generate all possible sequential orderings of an integer array.'),
  ('subsets-ii', 'Generate all unique power sets from an array that contains duplicate values.'),
  ('combination-sum-ii', 'Find unique combinations summing to a target where each element is used only once.'),
  ('word-search', 'Traverse a 2D grid to verify if a specific string can be spelled using adjacent cells.'),
  ('palindrome-partitioning', 'Split a string into the maximum possible groupings where every substring is a palindrome.'),
  ('letter-combinations-of-a-phone-number', 'Generate all possible text messages given a string of digits on a T9 keypad.'),
  ('n-queens', 'Place N queens on an N × N chessboard such that no two queens can attack each other.'),
  ('number-of-islands', 'Count the distinct groups of connected 1s (land) surrounded by 0s (water) in a grid.'),
  ('clone-graph', 'Create a deep copy of a connected undirected graph using its nodes and neighbors.'),
  ('max-area-of-island', 'Find the largest contiguous block of 1s in a binary grid.'),
  ('pacific-atlantic-water-flow', 'Identify coordinates where rain can successfully flow down into both bordering oceans.'),
  ('surrounded-regions', 'Capture and flip all Os that are completely locked in by Xs.'),
  ('rotting-oranges', 'Calculate the minutes required for rot to spread to all adjacent fresh oranges.'),
  ('walls-and-gates', 'Fill empty rooms in a grid with the exact distance to the nearest gate.'),
  ('course-schedule', 'Determine if all courses can be completed given a strict list of prerequisites (cycle detection).'),
  ('course-schedule-ii', 'Return the exact topological ordering required to finish all courses successfully.'),
  ('redundant-connection', 'Identify the single edge that creates a cycle in what should be a valid tree structure.'),
  ('number-of-connected-components-in-an-undirected-graph', 'Count the total number of distinct clusters in an undirected graph.'),
  ('graph-valid-tree', 'Verify if a given set of nodes and edges forms one single, connected, cycle-free tree.'),
  ('word-ladder', 'Find the shortest transformation sequence to morph a starting word into an ending word.'),
  ('reconstruct-itinerary', 'Order flight tickets alphabetically to form a continuous, valid travel path.'),
  ('min-cost-to-connect-all-points', 'Find the minimum spanning tree required to connect various coordinates on a 2D plane.'),
  ('network-delay-time', 'Calculate the total time required for a signal to reach every node in a directed network.'),
  ('swim-in-rising-water', 'Calculate the minimum time required before you can successfully swim to the bottom-right corner of a grid.'),
  ('alien-dictionary', 'Deduce the correct alphabetical order of letters from a sorted list of alien words.'),
  ('cheapest-flights-within-k-stops', 'Find the lowest flight cost to a destination allowing a maximum of k transfers.'),
  ('climbing-stairs', 'Calculate the distinct number of ways to climb n stairs taking 1 or 2 steps at a time.'),
  ('min-cost-climbing-stairs', 'Minimize the total cost to reach the top of a staircase given an array of step costs.'),
  ('house-robber', 'Maximize loot from a street of houses without robbing two adjacent properties.'),
  ('house-robber-ii', 'Maximize loot where houses are arranged in a continuous circle (first and last are connected).'),
  ('longest-palindromic-substring', 'Find the longest palindrome hidden inside a larger string.'),
  ('palindromic-substrings', 'Count the total exact number of distinct palindromes in a string.'),
  ('decode-ways', 'Count the number of valid ways to decode a number string back into alphabetical letters.'),
  ('coin-change', 'Find the absolute fewest number of coins needed to make up a specific monetary amount.'),
  ('maximum-product-subarray', 'Identify the contiguous subarray within an array that yields the largest mathematical product.'),
  ('word-break', 'Determine if a string can be entirely segmented into words found in a provided dictionary.'),
  ('longest-increasing-subsequence', 'Find the length of the longest strictly increasing progression of numbers in an array.'),
  ('partition-equal-subset-sum', 'Check if an array can be perfectly split into two subsets with identical sums.'),
  ('unique-paths', 'Count all possible routes from the top-left to the bottom-right of a grid moving only down or right.'),
  ('longest-common-subsequence', 'Find the longest sequential pattern shared between two distinct strings.'),
  ('best-time-to-buy-and-sell-stock-with-cooldown', 'Maximize market profit factoring in a mandatory 1-day cooldown between trades.'),
  ('coin-change-2', 'Count the total distinct combinations of coins that can make up a specific amount.'),
  ('target-sum', 'Find the total number of ways to assign + or - to array elements to equal a target.'),
  ('interleaving-string', 'Verify if a target string can be formed by perfectly interleaving two other strings.'),
  ('longest-increasing-path-in-a-matrix', 'Find the longest continuous path of increasing numbers navigating through a 2D grid.'),
  ('distinct-subsequences', 'Count the exact number of times a target string appears as a subsequence in a larger string.'),
  ('edit-distance', 'Calculate the minimum insertions, deletions, or substitutions required to convert one string into another.'),
  ('burst-balloons', 'Maximize coins collected by strategically bursting adjacent balloons on a 1D plane.'),
  ('regular-expression-matching', 'Implement regex matching rules with support for . (any character) and * (zero or more).'),
  ('maximum-subarray', 'Find the contiguous sequence of numbers within an array that results in the largest sum.'),
  ('jump-game', 'Determine if it is possible to reach the final index of an array based on jump limits.'),
  ('jump-game-ii', 'Find the minimum absolute number of jumps required to reach the end of the array.'),
  ('gas-station', 'Identify the starting station index required to successfully complete a full circular route.'),
  ('hand-of-straights', 'Verify if an array of cards can be perfectly divided into consecutive sets of a specific size.'),
  ('merge-triplets-to-form-target-triplet', 'Determine if a target triplet can be formed strictly using element-wise maximum operations.'),
  ('partition-labels', 'Split a string into the maximum number of chunks where each character only appears in one specific chunk.'),
  ('valid-parenthesis-string', 'Validate a bracket string where wildcards * can act as open, closed, or empty characters.'),
  ('insert-interval', 'Seamlessly merge a new interval into a strictly sorted, non-overlapping list of intervals.'),
  ('merge-intervals', 'Combine all overlapping intervals into an optimized, continuous set.'),
  ('non-overlapping-intervals', 'Find the minimum number of intervals to remove to eliminate all timeline overlaps.'),
  ('meeting-rooms', 'Check if it is chronologically possible for a person to attend all scheduled meetings.'),
  ('meeting-rooms-ii', 'Determine the minimum number of physical conference rooms required to hold all meetings.'),
  ('minimum-interval-to-include-each-query', 'Find the size of the smallest interval that fully covers specific query points.'),
  ('rotate-image', 'Rotate a 2D image matrix 90 degrees clockwise completely in-place.'),
  ('spiral-matrix', 'Unravel and return all elements of a 2D matrix in a continuous spiral order.'),
  ('set-matrix-zeroes', 'Set an entire row and column to zero if a single zero is detected in the matrix.'),
  ('happy-number', 'Determine if a number eventually resolves to 1 by repeatedly summing the squares of its digits.'),
  ('plus-one', 'Increment a large integer represented as an array of digits by one.'),
  ('powx-n', 'Mathematically calculate x raised to the power of n.'),
  ('multiply-strings', 'Calculate the product of two massive numbers represented strictly as strings.'),
  ('detect-squares', 'Count the number of ways to form an axis-aligned square from a dynamic stream of coordinates.'),
  ('single-number', 'Identify the lone non-repeating number in an array using an O(1) space bitwise approach.'),
  ('number-of-1-bits', 'Count the total number of set bits (1s) in a number''s binary representation.'),
  ('counting-bits', 'Return an array containing the exact 1-bit counts for every integer up to n.'),
  ('reverse-bits', 'Completely flip the binary bits of a 32-bit unsigned integer.'),
  ('missing-number', 'Find the one single missing integer in an array spanning from 0 to n.'),
  ('sum-of-two-integers', 'Add two numbers together without using the traditional + or - mathematical operators.'),
  ('reverse-integer', 'Safely reverse the digits of a signed 32-bit integer while handling overflow constraints.')
) AS v(slug, description)
WHERE q.slug = v.slug;
